apiVersion: v1
kind: Namespace
metadata:
  name: bhw-24-redis
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-creds
  namespace: bhw-24-redis
  labels:
    app: bhw-redis
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: redis-password
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: redis
  namespace: kube-system
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: redis
  targetNamespace: bhw-24-redis
  version: 18.16.0
  valuesContent: |-
    commonLabels:
      app: bhw-redis
    architecture: standalone
    master:
      persistence:
        enabled: true
    auth:
      enabled: true
      existingSecret: redis-creds
    networkPolicy:
      enabled: false
    tls:
      enabled: false
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: redis-policy
  namespace: bhw-24-redis
  labels:
    app: bhw-redis
spec:
  podSelector:
    matchLabels:
      app: bhw-redis
  policyTypes:
    - Egress
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: bhw-24
          podSelector:
            matchLabels:
              app: bhw
      ports:
        - protocol: TCP
          port: 6379
  egress: []
