[package]
name = "bhw-frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { version = "0.21.0", features = ["csr"] }
yew-router = { version = "0.18.0" }
gloo-console = "0.3.0"
gloo-net = { version = "0.5.0", features = ["json"]}
gloo-utils = "0.2.0"
rand = "0.8.5"
web-sys = "0.3.68"
wasm-bindgen-futures = "0.4.41"
serde = { version = "1.0", features = ["derive"]}
bhw-types = { path = "../types" }
thiserror = "1.0.57"
yew_icons = {git = "https://github.com/palkerecsenyi/yew_icons.git", features = ["FontAwesomeSolidUser", "FontAwesomeSolidPeopleGroup", "FontAwesomeSolidCircleXmark", "FontAwesomeSolidBars", "FontAwesomeSolidShuffle", "FontAwesomeSolidTrophy", "FontAwesomeSolidComments", "FontAwesomeSolidQuestion", "FontAwesomeSolidCircleInfo", "FontAwesomeSolidHeart", "FontAwesomeSolidUniversalAccess", "FontAwesomeSolidArrowLeft", "FontAwesomeSolidSpinner"]}
