[package]
name = "bhw-backend"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
figment = { version = "0.10", features = ["env", "toml"] }
serde = {version = "1.0", features = ["derive"]}
serde_json = "1"
env_logger = { version = "0.11" }
diesel = { version = "2.1.0", features = ["postgres", "r2d2", "uuid", "chrono"] }
uuid = { version = "1.7.0", features = ["v4"] }
chrono = "0.4.34"
bhw-types = { path = "../types" }
r2d2 = "0.8.10"
argon2 = "0.5.3"
rand = {version = "0.8.5", features=["getrandom"]}
hex = "0.4.3"
thiserror = "1.0.57"
