[package]
name = "bhw-backend"
version = "0.1.0"
edition = "2021"
rust-version = "1.80"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-session = { version = "0.10", features = ["redis-session"] }
actix-multipart = "0.7"
rust-s3 = { version = "0.35", features = ["tokio-native-tls"] }
figment = { version = "0.10", features = ["env", "toml"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
env_logger = { version = "0.11" }
log = "0.4"
argon2 = "0.5"
rand = { version = "0.9" }
hex = "0.4"
thiserror = "2.0"
mailgun-rs = { version = "1.0", features = ["rustls-tls"] }
mime = "0.3"
futures-util = "0.3"
regex = "1.11"
ldap3 = { version = "0.11", optional = true }
url = "2.5"
tokio = { version = "1.43", features = ["time", "fs"] }
actix-cors = "0.7"
passwords = { version = "3.1", features = ["common-password"] }
sea-orm = { version = "1.1", features = [
    "sqlx-postgres",
    "runtime-tokio-native-tls",
    "with-chrono",
    "with-uuid",
    "macros",
] }
uuid = { version = "1.14", features = ["v4"] }
chrono = "0.4"
reqwest = { version = "0.12", default-features = false }

bhw-migration = { path = "../migration" }
bhw-models = { path = "../models" }
bhw-types = { path = "../types" }

[features]
default = []
ldap = ["dep:ldap3"]
