[package]
name = "bhw-backend"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-session = { version = "0.9.0", features = ["redis-rs-session"] }
figment = { version = "0.10", features = ["env", "toml"] }
serde = {version = "1.0", features = ["derive"]}
serde_json = "1"
env_logger = { version = "0.11" }
log = "0.4.20"
argon2 = "0.5.3"
rand = {version = "0.8.5", features = ["getrandom"] }
hex = "0.4.3"
thiserror = "1.0.57"
mailgun-rs = "0.1.10"
futures-util = "0.3.30"
regex = "1.10.3"
ldap3 = {version = "0.11.3", optional = true}
url = "2.5.0"
tokio = {version = "1.36.0", features = ["time"] }
actix-cors = "0.7.0"
passwords = {version = "3.1.16", features = ["common-password"]}
sea-orm = { version = "0.12", features = ["sqlx-postgres", "runtime-tokio-rustls", "with-chrono", "with-uuid", "macros"] }
uuid = { version = "1.7.0", features = ["v4"] }
chrono = "0.4.34"
bhw-migration = { path = "../migration" }
bhw-models = { path = "../models" }

bhw-types = { path = "../types" }


[features]
default = ["ldap"]
ldap = ["dep:ldap3"]