//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "competition_group")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub join_code: String,
    pub group_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::website_user::Entity")]
    WebsiteUser,
}

impl Related<super::website_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebsiteUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
