//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use super::sea_orm_active_enums::RegistrationStageEnum;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "participant_registration")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub created_at: DateTime,
    pub created_by: String,
    pub stage: RegistrationStageEnum,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::website_user::Entity",
        from = "Column::UserId",
        to = "super::website_user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    WebsiteUser,
}

impl Related<super::website_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebsiteUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
