//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use super::sea_orm_active_enums::TShirtSizeEnum;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "website_user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub display_name: Option<String>,
    #[sea_orm(unique)]
    pub bath_username: String,
    pub password_hash: String,
    pub created_at: DateTime,
    #[sea_orm(column_type = "Text", nullable)]
    pub dietary_requirements: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub accessibility_requirements: Option<String>,
    pub group_id: Option<Uuid>,
    pub ldap_check_status: i16,
    pub t_shirt_size: Option<TShirtSizeEnum>,
    pub is_committee: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::competition_group::Entity",
        from = "Column::GroupId",
        to = "super::competition_group::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CompetitionGroup,
    #[sea_orm(has_one = "super::password_reset::Entity")]
    PasswordReset,
}

impl Related<super::competition_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CompetitionGroup.def()
    }
}

impl Related<super::password_reset::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PasswordReset.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
