name: Build and deploy frontend

on:
  push:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable
          targets: wasm32-unknown-unknown
      - name: Install trunk
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall -y trunk
      - name: Build with trunk
        run: trunk build --release --filehash false
        working-directory: ./packages/frontend
        env:
          BHW_FRONTEND_API_URL: "https://hack-api.bathcs.com"
          BHW_FRONTEND_USE_NETLIFY_IMAGE_CDN: "true"
      - name: Install binaryen for wasm-opt
        run: |
          sudo apt-get install -y binaryen
      - name: Optimise wasm binary size
        working-directory: ./packages/backend/dist
        run: |
          mv bhw-frontend_bg.wasm unoptimised.wasm
          wasm-opt unoptimised.wasm -Os -o bhw-frontend_bg.wasm
          rm unoptimised.wasm
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: ./packages/frontend/dist
          production-deploy: true
          fails-without-credentials: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
